sudo: required
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - "pip install git+git://github.com/TurboGears/crank.git"
  - "pip install git+git://github.com/TurboGears/backlash.git"
  - "pip install repoze.who"
  - "pip install coverage==4.2"
  - "pip install nose"
  - "pip install --no-use-wheel -e .[testing]"
  - "pip install --upgrade git+http://git.code.sf.net/p/merciless/code"

  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install git+git://github.com/TurboGears/tgext.chameleon_genshi.git; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install git+git://github.com/TurboGears/tgext.chameleon_genshi.git; fi
 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls && export HAS_COVERALLS=1; fi

script: "nosetests -v --with-coverage --cover-package=tg --cover-erase"

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
